export const ErrorCode = {
  BOARD_NOT_INITIALIZED: 'BOARD_NOT_INITIALIZED',
  BOARD_ALREADY_INITIALIZED: 'BOARD_ALREADY_INITIALIZED',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  COLUMN_NOT_FOUND: 'COLUMN_NOT_FOUND',
  COLUMN_NOT_EMPTY: 'COLUMN_NOT_EMPTY',
  COLUMN_NAME_EXISTS: 'COLUMN_NAME_EXISTS',
  INVALID_PRIORITY: 'INVALID_PRIORITY',
  INVALID_METADATA: 'INVALID_METADATA',
  INVALID_POSITION: 'INVALID_POSITION',
  MISSING_ARGUMENT: 'MISSING_ARGUMENT',
  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',
  PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_UPSTREAM_ERROR: 'PROVIDER_UPSTREAM_ERROR',
  PROVIDER_SYNC_REQUIRED: 'PROVIDER_SYNC_REQUIRED',
  PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode]

export class KanbanError extends Error {
  constructor(
    public code: ErrorCodeValue,
    message: string,
  ) {
    super(message)
    this.name = 'KanbanError'
  }
}
